spring.application.name=spb14-apiGateway

server.port=8085
eureka.client.service-url.defaultZone=http://localhost:8084/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

spring.cloud.gateway.routes[0].id=SPB10-EMPLOYEEPROJ
#spring.cloud.gateway.routes[0].uri=localhost:8081
spring.cloud.gateway.routes[0].uri=lb://SPB10-EMPLOYEEPROJ
spring.cloud.gateway.routes[0].predicates[0]=Path=/emp/**

spring.cloud.gateway.routes[1].id=SPB11-ACCOUNTPROJ
spring.cloud.gateway.routes[1].uri=lb://SPB11-ACCOUNTPROJ
spring.cloud.gateway.routes[1].predicates[0]=Path=/acc/**

spring.cloud.gateway.routes[2].id=SPB12-PLOTPROJ
spring.cloud.gateway.routes[2].uri=lb://SPB12-PLOTPROJ
spring.cloud.gateway.routes[2].predicates[0]=Path=/plot/**