spring.application.name=spb16-configServer
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/SurajPratapSingh2025/java
spring.cloud.config.server.git.search-paths=configServer
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=master

eureka.client.service-url.defaultZone=http://localhost:8084/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#Actuator monitoring
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always

#Logging
#logging.level.org.springframework.cloud.config=DEBUG

#Performance/Stability
#spring.cloud.config.server.git.timeout=10
#spring.cloud.config.server.git.force-pull=true


